### ISSUE TITLE
Django Rest Framework 3.4 compatibility

### ISSUE THREAD

**Issue by spyroslalos** [burke-software/django-report-builder#236]
Hey guys,

i followed the install instructions and urls work fine but i get no result whatsoever.

<img width="527" alt="screenshot 2016-06-30 17 22 59" src="https://cloud.githubusercontent.com/assets/5014547/16493861/6662f7a4-3ee7-11e6-89c4-8a503bcdd29f.png">

Any ideas?

**Comment by joej** [comment]
Same problem here -- lots of google hits for this. 

Things to try: (1) ensure rest_framework is installed in your settings.py with the session authentication; (2) do a 'manage.py collectstatic' on the command line

This gets me to a non-blank view at /report_buiilder/ URL. 

But, still ... no functionality, apparently.

**Comment by joej** [comment]
Now, on the client/browser side ... errors are piling up about /api/xxxxx failures. (code 500).

So, since the documentation is SPARSE for this code, I'll start reading the code and seeing what they're supposed to serve at /api endpoints. Probably a REST thing.

**Comment by joej** [comment]
Failing to serve any /api/ endpoints ... django log messages:

```

  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Python/2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Library/Python/2.7/site-packages/rest_framework/views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "/Library/Python/2.7/site-packages/rest_framework/views.py", line 454, in dispatch
    self.initial(request, *args, **kwargs)
  File "/Library/Python/2.7/site-packages/rest_framework/views.py", line 385, in initial
    self.check_permissions(request)
  File "/Library/Python/2.7/site-packages/rest_framework/views.py", line 318, in check_permissions
    if not permission.has_permission(request, self):
AttributeError: 'SessionAuthentication' object has no attribute 'has_permission'

```

**Comment by joej** [comment]
OK -- see issue #140 here.

This just doesn't work "out of the box" if you have any REST_FRAMEWORK in your settings.py. 
I've removed ALL of my rest settings, and I can now see a page at /report_builder/ and possibly a way of configuring in the /admin/

cheesuz ... cripes ...

**Comment by joej** [comment]
Nope -- blank reports, lots of browser side TypeError (handsome table.full.min.js - a.path.length) that are probably due to blank tables being created.

a few "lost connection" to /api/fields -- but works when I manually try the URL myself. It answers with "Method GET not allowed"

I can't save any report with fields in it. But, a blank/nothing report saved fine.
Failure to load (500) /report_builder/api/report/1/ ... which probably explains it all.

and, django complaining -- mostly that report_builder is sending "str" vs. "list/tuple" to read_only_fields ...

Internal Server Error: /report_builder/api/report/1/
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Python/2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/rest_framework/viewsets.py", line 87, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Library/Python/2.7/site-packages/rest_framework/views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "/Library/Python/2.7/site-packages/rest_framework/views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Library/Python/2.7/site-packages/rest_framework/mixins.py", line 69, in update
    serializer.is_valid(raise_exception=True)
  File "/Library/Python/2.7/site-packages/rest_framework/serializers.py", line 213, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "/Library/Python/2.7/site-packages/rest_framework/serializers.py", line 407, in run_validation
    value = self.to_internal_value(data)
  File "/Library/Python/2.7/site-packages/rest_framework/serializers.py", line 437, in to_internal_value
    validated_value = field.run_validation(primitive_value)
  File "/Library/Python/2.7/site-packages/rest_framework/serializers.py", line 561, in run_validation
    value = self.to_internal_value(data)
  File "/Library/Python/2.7/site-packages/rest_framework/serializers.py", line 597, in to_internal_value
    validated = self.child.run_validation(item)
  File "/Library/Python/2.7/site-packages/rest_framework/serializers.py", line 407, in run_validation
    value = self.to_internal_value(data)
  File "/Library/Python/2.7/site-packages/rest_framework/serializers.py", line 431, in to_internal_value
    fields = self._writable_fields
  File "/Library/Python/2.7/site-packages/django/utils/functional.py", line 33, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Library/Python/2.7/site-packages/rest_framework/serializers.py", line 346, in _writable_fields
    field for field in self.fields.values()
  File "/Library/Python/2.7/site-packages/rest_framework/serializers.py", line 339, in fields
    for key, value in self.get_fields().items():
  File "/Library/Python/2.7/site-packages/rest_framework/serializers.py", line 949, in get_fields
    extra_kwargs = self.get_extra_kwargs()
  File "/Library/Python/2.7/site-packages/rest_framework/serializers.py", line 1249, in get_extra_kwargs
    'Got %s.' % type(read_only_fields).__name__
TypeError: The `read_only_fields` option must be a list or tuple. Got str.

**Comment by bufke** [comment]
@joej please keep feedback constructive. This is a volunteer project. If you'd like to improve documentation pleaae submit a pull request.

**Comment by aprilmay** [comment]
This is due to a recent update of django_rest_framework: https://github.com/tomchristie/django-rest-framework/commit/c3b7fba918910553661095fed5d31e947a0fe2d6

The documentation (http://www.django-rest-framework.org/api-guide/serializers/#specifying-read-only-fields) is clear: "This option should be a list or tuple of field names".

In api/serializers.py, line 22: read_only_fields = ('id')
The fix is simple: read_only_fields = ('id', )

I believe this change is harmless.

**Comment by bufke** [comment]
Oh that is very clearly a bug. Thanks @aprilmay for the fix and @spyroslalos for the report

I don't think we are ready for rest framework 3.4 yet. But feel free to checkout master and verify this particular issue is fixed.

**Comment by bufke** [comment]
Here is another problem http://www.django-rest-framework.org/topics/3.4-announcement/#relational-choices-no-longer-displayed-in-options-requests

This affects the new report page which expects to find choices in the OPTIONS method.

Would anyone have time to fix this? I'll note the incompatibility it in the readme for now.

"If you want to override this new behavior you'll need to implement a custom metadata class."

I don't see any examples of actually doing this but I only spent a few minutes looking. Another solution would be to make another api call to get the choices.

**Comment by jangeador** [comment]
@bufke which Django Rest Framework should we be using then?

**Comment by bufke** [comment]
3.3 works fine. Just pushed a fix to master if you wouldn't mind checking it out.

**Comment by jangeador** [comment]
I tried it and now it does show the models however it **does not** add the report. The log shows:
```
[12/Aug/2016 11:09:21] "POST /report_builder/api/report/ HTTP/1.1" 400 61
```
As far as using 3.3 version of drf, that is a catch 22 as 3.3 is not compatible with django 1.10. It has an issue with urlpatterns.py.

**Comment by bufke** [comment]
Django 1.10 isn't supported - they removed a lot of internal mode meta functions that the project uses. I've started on it and have some ways to go.

I've never seen it not add the report as you describe - but if you are using 1.10 that may be the issue.

**Comment by bufke** [comment]
Going to close this one and make a Django 1.10 issue. I don't see any more problems from rest framework 3.4.
